name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Set up Git
        run: |
          git config --global user.name 'Razen'
          git config --global user.email '09876sp54321@gmail.com'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Change this to your output directory
